apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 05-master-kernelarg-selinuxpermissive
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - enforcing=0
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: routerint
  name: 05-routerint-kernelarg-selinuxpermissive
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - enforcing=0
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: routerpub
  name: 05-routerpub-kernelarg-selinuxpermissive
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - enforcing=0
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: infra
  name: 05-infra-kernelarg-selinuxpermissive
spec:
  config:
    ignition:
      version: 2.2.0
  kernelArguments:
    - enforcing=0
