apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    volume.beta.kubernetes.io/mount-options: rw,nfsvers=4,noexec
  name: jenkins-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jenkins
  nfs:
    path: /nfs1/jenkins
    server: 192.168.5.10
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

