apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat JBoss EAP 7.2
    openshift.io/image.dockerRepositoryCheck: "2021-06-01T07:13:56Z"
    openshift.io/provider-display-name: Red Hat, Inc.
    samples.operator.openshift.io/version: 4.6.15
    version: "1.2"
  generation: 19
  labels:
    samples.operator.openshift.io/managed: "true"
  name: jboss-eap72-openshift
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Red Hat JBoss EAP 7.2 S2I Image
      iconClass: icon-eap
      openshift.io/display-name: Red Hat JBoss EAP 7.2
      sampleContextDir: kitchensink
      sampleRef: openshift
      sampleRepo: https://github.com/jbossas/eap-quickstarts/openshift
      supports: eap:7.2,javaee:7,java:8
      tags: builder,eap,javaee,java,jboss,hidden
      version: "1.2"
    from:
      kind: DockerImage
      name: registry.oss2.fu.igotit.co.kr:5000/jboss-eap-72-openshift:1.2-23
    generation: 18
    importPolicy: {}
    name: "1.2"
    referencePolicy:
      type: Local
