apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-volume-01 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: alertmanager-main-db-alertmanager-main-0
    namespace: openshift-monitoring
  nfs:
    path: /nfs1/alert-storage-01
    server: 192.168.5.10
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

