apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume-01 
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: prometheus-k8s-db-prometheus-k8s-0
    namespace: openshift-monitoring
  nfs:
    path: /nfs1/prometheus-storage-01
    server: 192.168.5.10
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

